### ISSUE TITLE
what is the "primary log" in the log plugin?

### ISSUE THREAD

**Issue by davidxia** [spotify/ffwd-ruby#19]
Hi @udoprog,

If I specify

``` yaml
:output:
  - :type: "log"
```

in my ffwd.yaml, where does that log to if I have no other outputs defined? I see from the [source](https://github.com/spotify/ffwd/blob/master/lib/ffwd/plugin/log.rb#L31) that it logs to the "primary log." What does that mean?

**Comment by udoprog** [comment]
Primary log is either stdout, a stream (stdout/stderr), or to a file.

This is controlled using the `:logging` directive in the configuration file.

I've added an example which redirects logging to a file in 04a8256, hope this helps.

**Comment by davidxia** [comment]
great thanks!

**Comment by davidxia** [comment]
@udoprog So if don't have `:logging` does that mean log is stdout?

**Comment by udoprog** [comment]
@davidxia Yes
